# Generated by Django 4.2.1 on 2023-05-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_move',
            name='status_workplace',
            field=models.IntegerField(),
        ),
    ]
